### ISSUE TITLE
Gotcha Crash

### ISSUE THREAD

**Issue by kyman000** [OniSensei/Gotcha-v2.1#2] opened 2019-07-30 21:44 UTC
Upon launch gets an Initialization Error 
![Screenshot_1](https://user-images.githubusercontent.com/53496326/62167645-af55a980-b2f1-11e9-9eb8-cab331d17206.png)

**Comment by OniSensei** [comment] 2019-07-30 21:51
Normally when this happens it can be caused by a few things.

- You are running the bot from inside the zip and not extracting the folder to your desktop or documents etc.

- Somehow Discord.Net.Websocket.dll was removed from the folder 
   - Or you removed the exe from the folder without the rest of the contents

Etc.

Please also take note it has been recently discovered that this bot is not compatible with windows 7

**Comment by kyman000** [comment] 2019-07-30 21:58
ahh rip, most likely the windows 7 then.

**Comment by OniSensei** [comment] 2019-07-30 21:59
Unfortunetly its a restriction with the discord.net library used to read the incoming messages from pokecord.

**Comment by kyman000** [comment] 2019-07-30 21:59
wait a second, there isnt a discord websocket in the folder. just webhook and commands

**Comment by OniSensei** [comment] 2019-07-30 22:01
![img](https://imgur.com/p9ddT6l.png)
Fresh download, it should have it

**Comment by kyman000** [comment] 2019-07-30 22:02
But ahh ok, could be windows 7, i thought the exception was not being able to find discord webhook but it is websocket and it isnt in the folder.

**Comment by OniSensei** [comment] 2019-07-30 22:04
https://www.mediafire.com/file/5ypiuz8vffxolre/Discord.Net.WebSocket.dll/file
just put it in the same folder and lets see if it fixes. Doesnt hurt to try

**Comment by kyman000** [comment] 2019-07-30 22:06
ok that worked but it is also missing discord rest and core, just downloaded a fresh one and they are in the zip file lol, extracting now.

**Comment by OniSensei** [comment] 2019-07-30 22:06
Awesome, keep me posted.

**Comment by kyman000** [comment] 2019-07-30 22:07
discovered the problem, symantec (my anti virus) was deleting them.

**Comment by OniSensei** [comment] 2019-07-30 22:11
Glad to hear. Closing. Contact me on discord if you have any further issues, its usually easier. DefaulT#2648

**Closed by OniSensei** 2019-07-30 22:11 UTC
